### ISSUE TITLE
Operation Cleanup/Refactor

### ISSUE THREAD

**Issue by teddyzeenny** [emberjs/ember-inspector#360]
- [x] Add Babel support for ember-debug (https://github.com/emberjs/ember-inspector/pull/376)
- [ ] Upgrade to Ember 1.12 (does list-view support 1.12 yet?)
- [x] Refactor all EmberInspector code to use ES6 (@Mawaheb ) https://github.com/emberjs/ember-inspector/pull/372 https://github.com/emberjs/ember-inspector/pull/370 https://github.com/emberjs/ember-inspector/pull/368
- [ ] Refactor all ember-debug code to use ES6. See https://github.com/emberjs/ember-inspector/issues/377 for more details 
- [ ] Add comment blocks to all classes/methods/properties clearly explaining what each does. See https://github.com/emberjs/ember-inspector/issues/378 for more details.
- [ ] Replace Ember.ObjectController and Ember.ArrayController with Ember.Controller and remove item controllers. See https://github.com/emberjs/ember-inspector/issues/379 for more details. (@bjoska)
- [ ] Replace inline views with components See https://github.com/emberjs/ember-inspector/issues/380 for more details.
- [ ] Replace `bind-attr` with regular `attribute="{{prop}}"`. See https://github.com/emberjs/ember-inspector/issues/381 for more details. (@camskene)
- [ ] Code quality refactor
  - DRY up the code
  - Improve performance
  - Simplify complex functions
  - Remove all Ember observers
  - Replace two-way bindings with actions up bindings down
  - Custom registered objects such as port should be services
  - Remove `bind-attr`
  - When list-view supports Ember 1.13: angular bracket components, new action syntax
- [ ] Add a javascript style guide and stricter eslint rules
- [ ] Comment all css. Make sure it follows BEM conventions
- [ ] Add `ARCHITECTURE.md` file that explains how the inspector works
- [ ] Move methods that use private api into Ember core and add tests to them
- [ ] Extract ember-debug into its own repo (https://github.com/emberjs/ember-inspector/issues/339)

**Comment by Mawaheb** [comment]
I would like to contribute , Being new to this, (and the fact that this repo doesn't contain a CONTRIBUTING.md), I may need more details/advice if possible.

Do you have an IRC channel or any other means of communicating?
Thanks in advance.

**Comment by teddyzeenny** [comment]
@Mawaheb that's great! There's a [slack account](https://embercommunity.slack.com) for the Ember community with an ember-inspector channel. Feel free to mention me and I will try to reply asap. Does that sound like something you can use?

**Comment by Mawaheb** [comment]
:+1: Great! Thank you.

**Comment by locks** [comment]
@teddyzeenny someone needs to invite you in to be able to sign in :(

**Comment by rwjblue** [comment]
@locks @Mawaheb -> https://ember-community-slackin.herokuapp.com
